name: Setup Environment
description: Install and cache all project dependencies
inputs:
  NPM_USER:
    description: 'repository NPM_USER secret passed on'
    required: true
  NPM_PASS:
    description: 'repository NPM_PASS secret passed on'
    required: true
  NPM_EMAIL:
    description: 'repository NPM_EMAIL secret passed on'
    required: true
runs:
  using: "composite"
  steps:
    - name: Checkout code 🛎️
      uses: actions/checkout@v3

    - name: Setup node 🏗️
      uses: actions/setup-node@v1
      with:
        node-version: '16'

    - name: Get cache 🗄️
      id: cache
      uses: actions/cache@v3
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

    - name: Install dependencies 🔧
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        npm install -g npm-cli-login
        npm-cli-login -u ${{ inputs.NPM_USER }} -p ${{ inputs.NPM_PASS }} -e ${{ inputs.NPM_EMAIL }} -r https://registrynpm.storefrontcloud.io
        yarn --frozen-lockfile

