name: Release

on:
  workflow_call:
    secrets:
      NPM_USER:
        description: 'repository NPM_USER secret passed on'
        required: true
      NPM_PASS:
        description: 'repository NPM_PASS secret passed on'
        required: true
      NPM_EMAIL:
        description: 'repository NPM_EMAIL secret passed on'
        required: true 
    inputs:
      registry:
        description: "The registry to publish to"
        type: string
        required: true
        default: "https://registry.npmjs.org"

defaults:
  run:
    shell: bash

jobs:
  changelog:
    name: Changelog PR or Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies 🔧
        shell: bash
        run: |
          npm install -g npm-cli-login
          npm-cli-login -u ${{ secrets.NPM_USER }} -p ${{ secrets.NPM_PASS }} -e ${{ secrets.NPM_EMAIL }} -r ${{ inputs.registry}}
          yarn --frozen-lockfile

      - name: Create Release Pull Request or Publish
        id: changesets
        uses: changesets/action@v1
        with:
          version: yarn version
          publish: yarn publish
          commit: "ci: release"
          title: "ci: release"
        env:
          # Needs access to push to main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}