name: Release

on:
  workflow_call:
    secrets:
      NPM_USER:
        description: "repository NPM_USER secret passed on"
        required: true
      NPM_PASS:
        description: "repository NPM_PASS secret passed on"
        required: true
      NPM_EMAIL:
        description: "repository NPM_EMAIL secret passed on"
        required: true
    inputs:
      enterprise:
        description: "Flag to use enterprise registry"
        type: boolean
        required: false
        default: false

defaults:
  run:
    shell: bash

jobs:
  changelog:
    name: Changelog PR or Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies (Enterprise)
        if: ${{ inputs.enterprise }}
        shell: bash
        run: |
          npm install -g npm-cli-login
          npm-cli-login -u ${{ secrets.NPM_USER }} -p ${{ secrets.NPM_PASS }} -e ${{ secrets.NPM_EMAIL }} -r https://registrynpm.storefrontcloud.io
          HUSKY=0 yarn --frozen-lockfile

      - name: Install dependencies (OS)
        if: ${{ !inputs.enterprise }}
        shell: bash
        run: |
          HUSKY=0 yarn --frozen-lockfile

      - name: Create Release Pull Request or Publish
        id: changesets
        uses: changesets/action@v1
        with:
          version: yarn run changesets:version
          publish: yarn run changesets:publish
          commit: "ci: release"
          title: "ci: release"
          createGithubReleases: false

        env:
          # Needs access to push to main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_RELEASE_TOKEN }}

      - name: Log deployment to GitHub (start)
        if: steps.changesets.outputs.published == 'true'
        uses: bobheadxi/deployments@v1
        id: deployment
        with:
            step: start
            desc: ${{ steps.changesets.outputs.publishedPackages }}
            env: production


      - name: Log deployment to GitHub (end)
        if: steps.changesets.outputs.published == 'true'
        uses: bobheadxi/deployments@v1
        with:
           step: finish
           status: success
           env: ${{ steps.deployment.outputs.env }}
           deployment_id: ${{ steps.deployment.outputs.deployment_id }}
