name: Release

on:
  workflow_call:
    secrets:
      NPM_USER:
        description: "repository NPM_USER secret passed on"
        required: false
      NPM_PASS:
        description: "repository NPM_PASS secret passed on"
        required: false
      NPM_EMAIL:
        description: "repository NPM_EMAIL secret passed on"
        required: false
    inputs:
      enterprise:
        description: "Flag to use enterprise registry"
        type: boolean
        required: false
        default: false

defaults:
  run:
    shell: bash

jobs:
  changelog:
    name: Changelog PR or Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.node-version'

      - name: Log into Verdaccio
        if: ${{ inputs.enterprise }}
        shell: bash
        run: |
          npm install -g npm-cli-login
          npm-cli-login -u "${{ secrets.NPM_USER }}" -p "${{ secrets.NPM_PASS }}" -e "${{ secrets.NPM_EMAIL }}" -r https://registrynpm.storefrontcloud.io

      - name: Install dependencies
        shell: bash
        run: HUSKY=0 yarn --frozen-lockfile

      - name: Create Release Pull Request or Publish
        id: changesets
        uses: changesets/action@v1.4.5
        with:
          version: yarn run changesets:version
          publish: yarn run changesets:publish
          commit: "ci: release"
          title: "ci: release"
          createGithubReleases: true
        env:
          # Needs access to push to main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_RELEASE_TOKEN }}
