name: Continous Integration
inputs:
  NPM_USER:
    description: 'repository NPM_USER secret passed on'
    required: true
  NPM_PASS:
    description: 'repository NPM_PASS secret passed on'
    required: true
  NPM_EMAIL:
    description: 'repository NPM_EMAIL secret passed on'
    required: true

on:
  workflow_call:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: "0"

      - name: Setup node
        uses: actions/setup-node@v1
        with:
        node-version: '16'

      - name: Setup node
        uses: actions/setup-node@v1
        with:
        node-version: '16'

      - name: Install dependencies
        shell: bash
        run: |
          npm install -g npm-cli-login
          npm-cli-login -u ${{ inputs.NPM_USER }} -p ${{ inputs.NPM_PASS }} -e ${{ inputs.NPM_EMAIL }} -r https://registrynpm.storefrontcloud.io
          yarn --frozen-lockfile

      - name: Run linter on changed files 🧹
        uses: tj-actions/eslint-changed-files@v18
        with:
          config_path: "./eslintrc.json"
          ignore_path: "/.eslintignore"
          file_extensions: |
            packages/**/*.ts
            packages/**/*.vue
