name: Continous Integration

on:
  workflow_call:
    secrets:
      NPM_USER:
        description: 'repository NPM_USER secret passed on'
        required: true
      NPM_PASS:
        description: 'repository NPM_PASS secret passed on'
        required: true
      NPM_EMAIL:
        description: 'repository NPM_EMAIL secret passed on'
        required: true    

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code 🛎️
        uses: actions/checkout@v3

      - name: Setup node 🏗️
        uses: actions/setup-node@v1
        with:
          node-version: '16'

      - name: Get cache 🗄️
        id: cache
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies 🔧
        if: steps.cache.outputs.cache-hit != 'true'
        shell: bash
        run: |
          npm install -g npm-cli-login
          npm-cli-login -u ${{ secrets.NPM_USER }} -p ${{ secrets.NPM_PASS }} -e ${{ secrets.NPM_EMAIL }} -r https://registrynpm.storefrontcloud.io
          yarn --frozen-lockfile

      - name: Run linter on changed files 🧹
        uses: tj-actions/eslint-changed-files@v18
        with:
          config_path: "./.eslintrc.json"
          ignore_path: "./.eslintignore"
          token: ${{ secrets.GITHUB_TOKEN }}
          file_extensions: |
            **/*.ts
            **/*.vue
